const pool = require('../db');
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Fetch billing info
async function getBills(req, res) {
    try {
        const [rows] = await pool.query("SELECT * FROM bills");
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify(rows));
    } catch (err) {
        console.error('Error fetching bills:', err);
        res.writeHead(500);
        res.end(JSON.stringify({ error: err.message }));
    }
}

// Generate PDF bill
async function generateBillPDF(req, res) {
    const billId = req.url.split('/')[4]; // /api/bills/pdf/{id}

    try {
        const [bills] = await pool.query(`
      SELECT b.*, p.name as patient_name, p.contact, p.address 
      FROM bills b 
      JOIN patients p ON b.patient_id = p.patient_id 
      WHERE b.bill_id = ?
    `, [billId]);

        if (bills.length === 0) {
            res.writeHead(404);
            res.end('Bill not found');
            return;
        }

        const bill = bills[0];

        const doc = new PDFDocument();
        const fileName = `bill_${billId}_${Date.now()}.pdf`;
        const reportsDir = path.join(__dirname, '..', '..', 'reports');

        // Ensure reports directory exists
        if (!fs.existsSync(reportsDir)) {
            fs.mkdirSync(reportsDir);
        }

        const filePath = path.join(reportsDir, fileName);

        doc.pipe(fs.createWriteStream(filePath));
        doc.pipe(res);

        // PDF Header
        doc.fontSize(24).text('MEDITRACK GENERAL HOSPITAL', 50, 40, { align: 'center' });
        doc.fontSize(12).text('123 Healthcare Avenue, Medical District', 50, 70, { align: 'center' });
        doc.text('Mumbai, Maharashtra 400001 | Phone: +91-22-1234-5678', 50, 85, { align: 'center' });
        doc.text('Email: info@meditrack.com | Website: www.meditrack.com', 50, 100, { align: 'center' });

        doc.moveTo(50, 120).lineTo(550, 120).stroke();

        doc.fontSize(18).text('MEDICAL BILL INVOICE', 50, 140, { align: 'center' });
        doc.moveTo(50, 165).lineTo(550, 165).stroke();

        // Bill Details
        doc.fontSize(12)
            .text(`Bill ID: ${bill.bill_id}`, 50, 185)
            .text(`Date: ${new Date(bill.bill_date).toLocaleDateString()}`, 350, 185)
            .text(`Patient Name: ${bill.patient_name}`, 50, 205)
            .text(`Contact: ${bill.contact}`, 50, 225)
            .text(`Address: ${bill.address}`, 50, 245);

        // Charges Table
        doc.fontSize(14).text('CHARGES BREAKDOWN', 50, 285);
        doc.moveTo(50, 305).lineTo(550, 305).stroke();

        doc.fontSize(12)
            .text('Room Charges:', 50, 325).text(`Rs. ${bill.room_charges}`, 450, 325)
            .text('Medicine Charges:', 50, 345).text(`Rs. ${bill.medicine_charges}`, 450, 345)
            .text('Doctor Fee:', 50, 365).text(`Rs. ${bill.doctor_fee}`, 450, 365);

        doc.moveTo(50, 385).lineTo(550, 385).stroke();
        doc.fontSize(16).text('TOTAL AMOUNT:', 50, 405).text(`Rs. ${bill.total_amount}`, 450, 405);
        doc.fontSize(12).text(`Payment Status: ${bill.status}`, 50, 435);

        // Footer
        doc.moveTo(50, 480).lineTo(550, 480).stroke();
        doc.fontSize(10)
            .text('Thank you for choosing MediTrack General Hospital', 50, 500, { align: 'center' })
            .text('For any queries, please contact us at +91-22-1234-5678 or info@meditrack.com', 50, 515, { align: 'center' })
            .text('Get well soon!', 50, 535, { align: 'center' });

        // Auto-generated footer
        doc.moveTo(50, 560).lineTo(550, 560).stroke();
        doc.fontSize(8).text('This invoice is auto-generated by MediTrack Hospital Management System', 50, 570, { align: 'center' });
        doc.text(`Generated on: ${new Date().toLocaleString()}`, 50, 580, { align: 'center' });

        res.writeHead(200, {
            'Content-Type': 'application/pdf',
            'Content-Disposition': `inline; filename="${fileName}"`
        });

        doc.end();

    } catch (err) {
        console.error('Error generating PDF:', err);
        res.writeHead(500);
        res.end(JSON.stringify({ error: err.message }));
    }
}

// Mark bill as paid
async function markBillPaid(req, res) {
    const billId = req.url.split('/')[3];

    if (!billId || !Number.isInteger(Number(billId)) || Number(billId) <= 0) {
        res.writeHead(400, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: "Invalid bill ID" }));
        return;
    }

    try {
        console.log(`💰 Marking bill ${billId} as paid...`);
        const [result] = await pool.query(
            "UPDATE bills SET status = 'Paid' WHERE bill_id = ?",
            [Number(billId)]
        );

        if (result.affectedRows === 0) {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Bill not found" }));
            return;
        }

        console.log(`✅ Bill ${billId} marked as paid successfully`);
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ message: "Bill marked as paid successfully" }));
    } catch (err) {
        console.error('Error marking bill as paid:', err);
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: err.message }));
    }
}

// Get single bill by ID
async function getBillById(req, res) {
    const billId = req.url.split('/')[3];
    try {
        const [bills] = await pool.query(`
            SELECT b.*, p.name as patient_name 
            FROM bills b 
            JOIN patients p ON b.patient_id = p.patient_id 
            WHERE b.bill_id = ?
        `, [billId]);
        
        if (bills.length === 0) {
            res.writeHead(404, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: "Bill not found" }));
            return;
        }
        
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify(bills[0]));
    } catch (err) {
        console.error('Error fetching bill:', err);
        res.writeHead(500, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ error: err.message }));
    }
}

// Update bill
async function updateBill(req, res) {
    const billId = req.url.split('/')[3];
    let body = '';
    req.on('data', chunk => { body += chunk.toString(); });
    req.on('end', async () => {
        try {
            const { room_charges, medicine_charges, doctor_fee, total_amount } = JSON.parse(body);
            
            await pool.query(
                'UPDATE bills SET room_charges = ?, medicine_charges = ?, doctor_fee = ?, total_amount = ? WHERE bill_id = ?',
                [room_charges, medicine_charges, doctor_fee, total_amount, billId]
            );
            
            res.writeHead(200, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ message: 'Bill updated successfully' }));
        } catch (error) {
            console.error('Error updating bill:', error);
            res.writeHead(500, { "Content-Type": "application/json" });
            res.end(JSON.stringify({ error: error.message }));
        }
    });
}

module.exports = { getBills, generateBillPDF, markBillPaid, getBillById, updateBill };
